version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: assessment-users-service
    ports:
      - "8088:8088"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/usersdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
    networks:
      - application-network
    depends_on:
      - mysqldb
  
  mysqldb:
    image: mysql:8.0
    container_name: my-sql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: usersdb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - application-network

volumes:
  mysql_data:

networks:
  application-network:
